SimpleLibrarySystem: SimpleStudent.o SimpleLibrarySystem.o main.o
			g++ SimpleStudent.o SimpleLibrarySystem.o main.o -o SimpleLibrarySystem

SimpleStudent.o : SimpleStudent.cpp 
		g++ -c SimpleStudent.cpp

SimpleLibrarySystem.o : SimpleLibrarySystem.cpp
				g++ -c SimpleLibrarySystem.cpp

main.o : main.cpp
		g++ -c main.cpp